name: CaseyProvost.com
description: These are the mad ramblings of a Ruby wanderer, father, cyclist, and super nerd.
meta_description: "These are the mad ramblings of a Ruby wanderer, code spalunker, father, cyclist, and super nerd."

aboutPage: true

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems: [jekyll-paginate]
paginate: 20
baseurl: /
domain_name: "https://caseyprovost.com"
google_analytics: 'UA-89616188-1'
disqus: true
disqus_shortname: 'caseyprovost'

# Details for the RSS feed generator
url:            'https://caseyprovost.com'
author:         'Casey Provost'
authorTwitter:  'caseyprovost'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
