# Site settings
title: CaseyProvost.com
email: caseyr.provost@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  These are the mad ramblings of a Ruby wanderer, code spalunker, father,
  cyclist, and super nerd. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://caseyprovost.com" # the base hostname & protocol for your site
twitter_username: caseyprovost
github_username:  caseyprovost

# Build settings
markdown: kramdown
